server:
  port: 8080

spring:
  profiles:
    active: local
  cloud:
    gcp:
      sql:
        enabled: false
      storage:
        enabled: true
        bucket: ${GCP_STORAGE_BUCKET}

  threads:
    virtual:
      enabled: true

  application:
    name: Club-Rom-Concept

api:
  security:
    token:
      secret: ${JWT_SECRET}

resend:
  api:
    key: ${RESEND_API_KEY}

totem:
  api:
    key: ${TOTEM_API_KEY}

