server:
  port: 8080

spring:
  cloud:
    gcp:
      sql:
        enabled: false
      storage:
        enabled: true
        bucket: rom_society

  threads:
    virtual:
      enabled: true

  application:
    name: Club-Rom-Concept

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
    show-sql: true

  flyway:
    enabled: true

api:
  security:
    token:
      secret: ${JWT_SECRET}

resend:
  api:
    key: ${RESEND_API_KEY}

totem:
  api:
    key: ${TOTEM_API_KEY}